sudo: required
language: go
go:
- 1.11.2

addons:
  apt:
    packages:
    - gcc-mingw-w64-x86-64
    - binutils-mingw-w64-x86-64

services:
- docker

install:
- docker pull therecipe/qt:windows_64_shared_512
- go get -v -tags=no_env github.com/therecipe/qt/cmd/...

script:
- go get -d -v ./...
- x86_64-w64-mingw32-windres icon.rc -o icon_win64.syso
- $GOPATH/bin/qtdeploy -docker build windows